version: '3.9'
services:
  app:
    build: 
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports: 
      - 8000:8000
    volumes: 
      - ./app:/app
    environment: 
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=aclab
      - DB_PASS=aclab@6768  
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment: 
      - POSTGRES_DB=devdb
      - POSTGRES_USER=aclab
      - POSTGRES_PASSWORD=aclab@6768